pki:
  ca: ca.crt
  cert: b.crt
  key: b.key

static_host_map:
  "192.168.100.1": ["127.0.0.1:10001"]

logging:
  level: info

listen:
  host: 127.0.0.1
  port: 10002

port_forwarding:
  enable_without_rules: true
  outbound:
    - listen_address: "127.0.0.1:15002"
      dial_address: "192.168.100.1:5201"
      protocols: [tcp, udp]

tun:
  disabled: true
  mtu: 1300

firewall:
  outbound:
    - port: any
      proto: udp
      host: any
    - port: 5201
      proto: any
      host: any
