name: smoke
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/smoke**'
      - '**Makefile'
      - '**.go'
      - '**.proto'
      - 'go.mod'
      - 'go.sum'
jobs:

  smoke:
    name: Run multi node smoke test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6

    - uses: actions/setup-go@v6
      with:
        go-version: '1.26'
        check-latest: true

    - name: Smoke Docker
      run: make smoke-docker

    - name: Smoke Docker IPv6 overlay
      run: make smoke-docker-ipv6

    - name: Smoke Relay Docker
      run: make smoke-relay-docker

    - name: Smoke Docker boringcrypto
      run: make boringcrypto smoke-docker

    - name: Smoke Docker fips140
      run: make fips140-all smoke-docker

    timeout-minutes: 10
